Completes issue #1
tedlasai/GradeHelper pull request #5
Opened 2021-09-26 17:15 UTC by itsianmac

Add functionality for writing out all grade and student numbers to single csv

2021-09-26 22:13 UTC, JustinSo1 commented
Just a tiny change but otherwise LGTM!

2021-09-27 15:24 UTC, tedlasai approved these changes
Looks fine.

2021-09-27 18:44 UTC, JustinSo1 requested changes

2021-09-27 18:45 UTC, JustinSo1 commented on gradehelper.py
> +                    createMessagePopUpBox(e)
Haha omg I forgot to publish my review sorry Ian

2021-09-29 16:13 UTC, JustinSo1 approved these changes

2021-09-29 16:14 UTC, merged